name: c-linter

on: [pull_request]
jobs:
  c-linter:
    permissions:
      contents: write
      pull-requests: write 
      issues: read
      packages: none
    name: c-linter
    runs-on: ubuntu-latest

    steps:
      - name: c-linter
        id: lint
        uses: ArtificialAmateur/cpp-linter-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            static analysis for the cpp code
            ```
            hello
            ```      
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 