name: c-linter

on: [pull_request]
jobs:
  c-linter:
    permissions:
      contents: 'read'
      id-token: 'write'
      issues: 'write'
    name: c-linter
    runs-on: ubuntu-latest

    steps:
      - name: c-linter
        uses: ArtificialAmateur/cpp-linter-action@master
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
