name: Static Code Analysis

on:
  pull_request:
    branches:
      - main

jobs:
  static_code_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Cppcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck

      - name: Run Cppcheck
        run: |
          cppcheck --enable=all --inconclusive --xml --xml-version=2 . 2> cppcheck_report.xml

      - name: Comment on Pull Request
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const { createCheckRun } = require('./node_modules/octokit/dist-node/checks/create-check-run');
            const { createComment } = require('./node_modules/octokit/dist-node/issues/create-comment');

            // Read the Cppcheck report
            const report = fs.readFileSync('cppcheck_report.xml', 'utf8');

            // Create a check run
            const check = await createCheckRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Cppcheck',
              head_sha: context.payload.pull_request.head.sha,
              status: 'completed',
              conclusion: 'neutral',
              output: {
                title: 'Static Code Analysis (Cppcheck)',
                summary: 'Static code analysis report generated by Cppcheck',
                text: report,
                annotations: []
              }
            });

            // Parse the Cppcheck report and add annotations to the check run
            const parser = new DOMParser();
            const xmlDoc = parser.parseFromString(report, 'text/xml');
            const errors = xmlDoc.getElementsByTagName('error');

            for (let i = 0; i < errors.length; i++) {
              const error = errors[i];
              const file = error.getAttribute('file');
              const line = error.getAttribute('line');
              const message = error.getAttribute('msg');

              await createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: `Cppcheck found an issue in ${file} at line ${line}: ${message}`
              });

              check.output.annotations.push({
                path: file,
                start_line: parseInt(line),
                end_line: parseInt(line),
                annotation_level: 'failure',
                message: message
              });
            }

            // Update the check run with the annotations
            await createCheckRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Cppcheck',
              check_run_id: check.data.id,
              status: 'completed',
              conclusion: 'neutral',
              output: check.output
            });