name: c-linter

on: [pull_request]
jobs:
  c-linter:
    permissions:
      contents: 'read'
      id-token: 'write'
      issues: 'write'
    name: c-linter
    runs-on: ubuntu-latest

    steps:
      - name: c-linter
        uses: ArtificialAmateur/cpp-linter-action@master
      - name: Post result to PR
        uses: mshick/add-pr-comment@v1
        with:
          message: ${{ env.MESSAGE }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default

    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
