name: CppCheck
on:
  pull_request:
    branches: [main]

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install cppcheck
      run: sudo apt-get install cppcheck
    - name: Run cppcheck
      run: cppcheck --enable=all .
    - name: Save cppcheck results
      if: always()
      run: cppcheck --enable=all . 2> CppCheck.txt
    - name: Comment on pull request with CppCheck results
      uses: actions/github@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          CppCheck Results:
          ```
          $(cat CppCheck.txt)
          ```
