name: cppcheck-action-test
on:
  pull_request:
    types:
      - closed

jobs:
  build:
    name: cppcheck test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
        with:
            ref: ${{ github.event.pull_request.head.sha }}

      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          output_file: ./CppCheckReport.txt
          
        
      - name: publish report    
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main'
# add comments
